export const COUNTER_ACTIONS = {
  INCREMENT_ASYNC: "INCREMENT_ASYNC",
  INCREMENT_ASYNC_SUCCESS: "INCREMENT_ASYNC_SUCCESS",
  INCREMENT_ASYNC_FAILURE: "INCREMENT_ASYNC_FAILURE",
  INCREMENT: "INCREMENT",
  INCREMENT_SUCCESS: "INCREMENT_SUCCESS",
  DECREMENT: "DECREMENT",
  DECREMENT_SUCCESS: "DECREMENT_SUCCESS",
  DECREMENT_ASYNC: "DECREMENT_ASYNC",
  DECREMENT_ASYNC_SUCCESS: "DECREMENT_ASYNC_SUCCESS",
  RESET: "RESET",
  RESET_SUCCESS: "RESET_SUCCESS",
  SET_VALUE: "SET_VALUE",
  SET_STATUS: "SET_STATUS",

  // Dialog actions
  HANDLE_SOMETHING: "HANDLE_SOMETHING",
  SHOW_DIALOG: "SHOW_DIALOG",
  HIDE_DIALOG: "HIDE_DIALOG",
  SET_DIALOG_OPTIONS: "SET_DIALOG_OPTIONS",
  CLEAR_DIALOG_OPTIONS: "CLEAR_DIALOG_OPTIONS",

  HANDLE_SOMETHING_WITH_ACTIONS_HANDLER:
    "HANDLE_SOMETHING_WITH_ACTIONS_HANDLER",
  SHOW_DIALOG_WITH_ACTIONS_HANDLER: "SHOW_DIALOG_WITH_ACTIONS_HANDLER",
  HIDE_DIALOG_WITH_ACTIONS_HANDLER: "HIDE_DIALOG_WITH_ACTIONS_HANDLER",
  SET_DIALOG_OPTIONS_WITH_ACTIONS_HANDLER:
    "SET_DIALOG_OPTIONS_WITH_ACTIONS_HANDLER",
  CLEAR_DIALOG_OPTIONS_WITH_ACTIONS_HANDLER:
    "CLEAR_DIALOG_OPTIONS_WITH_ACTIONS_HANDLER",
};
